### ISSUE TITLE
Asking: 상품 정렬 기능 관련 커스텀 훅 내 API 통신 문제

### ISSUE THREAD

**Issue by wSeungMi** [PhoenixFE/orum-market-front#127]
## 🤔 어떤 이슈인가요?
상품 정렬 기능 로직과 API 통신에 대한 질문입니다.

## ✍️ 자세한 내용을 적어주세요.
현재 SearchPage.tsx의 정렬 기능을 API 연결로 변경하는 작업을 진행하고 있습니다.
기존 코드는 SearchPage에서 NavigationBar 컴포넌트에서 실행되는 select box의 값을 받아오기위해 useSort의 set함수를 props로 넘겨주고,
받아온 props 값은 useSort 커스텀훅에 넘겨져서 일치하는 정렬 키워드를 통해 상품 리스트를 렌더링 해주고 있다는 것까지는 파악한 상태입니다.

이 부분을 API 통신을 통해 받아온 데이터로 변환해주려면 select box에서 받아온 값을 useSort에 넘겨줬을 때
useSort에서 해당 키워드를 가지고 get 요청을해서 response된 데이터를 상태값에 담아 return 시켜주면 되지 않을까..?라는 생각을 했는데요.
이 때, 커스텀 훅에 API 통신을 넣어도 괜찮은 것인지에 대한 확신이 서지 않습니다.

1. 커스텀 훅에서 API 통신을 해도 되는지
2. 제가 생각한 로직대로 진행해도 되는지

이 두 부분에 대한 의견을 여쭙고 싶어 질문드리니, 확인부탁드립니다!

**Comment by jingoworld** [comment]
커스텀 훅을 만든 이유부터 파악해보시면 의외로 쉽게 접근하실 수 있을 거 같습니다.
그러면서 과연 내가 쓰려는 API 통신에서 이 커스텀 훅이 꼭 필요한지? 필요하다면 코드의 어느 부분이 적용되고, 어느 부분이 불필요한지 등을 추려내야겠죠.
프론트에서 연산하던 작업을 백엔드에서 처리하게끔하고, 그 API를 사용하는 것이라는 것에 초점 맞춰서 잘 파악해보세요.

**Comment by wSeungMi** [comment]
네 참고하겠습니다. 감사합니다!
